name: Calculate test coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        version: "0.9.7"
    - name: Install Python
      run: uv python install
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Run tests
      run: uv run pytest tests --cov=wosfile --cov-report xml:coverage.xml --cov-report term
    - name: Upload coverage report
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
